### ISSUE TITLE
Looking for a sample project

### ISSUE THREAD

**Issue by architarya212** [secdec/codepulse#14]
i would be really thankful if you upload a real time project or a sample project to know the insight of code pulse..thank you

**Comment by leRadwan** [comment]
For those looking for a sample project to use with Code Pulse, we recommend using  the [OWASP Webgoat](https://www.owasp.org/index.php/Category:OWASP_WebGoat_Project) or [WAVSEP](https://code.google.com/p/wavsep/) projects.
