### ISSUE TITLE
Installing on OpenSuse problem

### ISSUE THREAD

**Issue by marioskourtesis** [secdec/codepulse#15]
This is my terminal output after installing the dependencies one by one.

kour@linux-fhgw:~/Downloads/codepulse> chmod +x codepulse
kour@linux-fhgw:~/Downloads/codepulse> ./codepulse 
./codepulse: error while loading shared libraries: libXtst.so.6: cannot open shared object file: No such file or directory
kour@linux-fhgw:~/Downloads/codepulse> ./codepulse 
./codepulse: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
kour@linux-fhgw:~/Downloads/codepulse> ./codepulse 
./codepulse: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
./codepulse: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
kour@linux-fhgw:~/Downloads/codepulse> ./codepulse 
./codepulse: error while loading shared libraries: libudev.so.0: cannot open shared object file: No such file or directory
kour@linux-fhgw:~/Downloads/codepulse> ./codepulse 

(codepulse:15866): Gtk-WARNING **: Unable to locate theme engine in module_path: "oxygen-gtk",

(codepulse:15866): Gtk-WARNING **: Unable to locate theme engine in module_path: "oxygen-gtk",
ATTENTION: default value of option force_s3tc_enable overridden by environment.
[15866:1016/005256:WARNING:simple_index_file.cc(338)] Could not map Simple Index file.
[15866:1016/005256:INFO:simple_index_file.cc(437)] Simple Cache Index is being restored from disk.

At the time all of the dependencies were installed I got the problem shown in the screenshot.
![owasp code pulse error](https://cloud.githubusercontent.com/assets/4330999/4655853/a9563368-54ca-11e4-810e-a26b94a1714f.png)
My System is OpenSuse 13.1

**Comment by leRadwan** [comment]
Marios, we've since release version 1.1.3 of Code Pulse that addresses a number of issues hopefully including the one you've run into. Please try that version and let us know if you still run into problems. For now I'm closing this issue.

**Comment by marioskourtesis** [comment]
Hello leRadwan ,
Thank you very much for your reply. Unfortunately It has been years since I opened that issue and nowadays I am not running OpenSuse. Although I am gonna give test the latest version on my Mint Box. 
Cheers
Marios
